### ISSUE TITLE
exception when running LXStudio on windows

### ISSUE THREAD

**Issue by rowr111** [heronarts/LXStudio#13]
When I click 'run' from within Processing, I get the following exception although it launches.  I'm running Windows 10. The error looks the same as what Ben reported [here](https://github.com/treeoftenere/Tenere/issues/14)?

RunnableTask.run(): A caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued true[executed false, flushed false], tTotal 17 ms, tExec 0 ms, tQueue 17 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <3fb7006d, b6918ab>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <3fb7006d, b6918ab>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl$ResizableAction.run(WindowImpl.java:2118)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:450)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setResizable(WindowImpl.java:2154)
	at com.jogamp.newt.opengl.GLWindow.setResizable(GLWindow.java:370)
	at processing.opengl.PSurfaceJOGL$5.run(PSurfaceJOGL.java:452)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:127)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
DefaultEDT.run(): Caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued false[executed true, flushed false], tTotal 5021 ms, tExec 5004 ms, tQueue 17 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <3fb7006d, b6918ab>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <3fb7006d, b6918ab>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl$ResizableAction.run(WindowImpl.java:2118)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:450)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setResizable(WindowImpl.java:2154)
	at com.jogamp.newt.opengl.GLWindow.setResizable(GLWindow.java:370)
	at processing.opengl.PSurfaceJOGL$5.run(PSurfaceJOGL.java:452)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:127)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
OpenGL error 1280 at top endDraw(): invalid enumerant

**Comment by jkbelcher** [comment]
This has been an ongoing problem I'm not sure has been figured out.  I have found it can be avoided by adding a custom UI component in the onUIReady() method, so that pixels are not the first visual object drawn:
```
    public void onUIReady(LXStudio lx, LXStudio.UI ui) {
        ui.preview.addComponent(new UIWalls(model));
    }
```
The UIWalls class is from an old example project, you can find a copy of it here:
https://github.com/jkbelcher/JouleCode/blob/master/src/UIWalls.java

**Comment by mcslee** [comment]
Very weird. Is this happening with the stock LXStudio project? Or have you made your own project with any modifications? The most common culprit is too much time being spent in initialization inside of your setup() method. You can try setting RESIZABLE = false in your project also to possibly contend with this issue.

But main first question I have is whether you are building a big custom model or anything like that in your code.

Long-term, I may just have to move a lot of the LX-bootstrapping and initialization out of the setup() method and push it into the first draw(), since there seems to be this weird GL timing issue that goes on with the Processing initialization scheme.
